# app.yaml
runtime: nodejs22
env: standard
instance_class: F1
 
env_variables:
  JWT_SECRET: "ourCATSforMAPteam@Irina@Hung@Sam@Mahima@Luc!"
  EMAIL: "catsformapapp@gmail.com"
  EMAIL_PASSWORD: "thdm tkqy syqh cwgk"
  CLOUD_SQL_CONNECTION_NAME: "catsformap:us-central1:catmap-db"

handlers:

  # Serve React app's static files
  - url: /(.*\.(js|css|png|jpg|svg|ico|webp|json|txt|woff2?))
    static_files: frontend/dist/\1
    upload: frontend/dist/.*

  # Route API requests to Node.js backend
  - url: /api/.*
    script: auto

  # Default route to serve React's index.html
  - url: /.*
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html



  