runtime: nodejs22

handlers:
  - url: /api/.*
    script: backend/server.js

  - url: /(.*\.(js|css|html|png|jpg|jpeg|gif|svg|ico))$
    static_files: frontend/\1
    upload: frontend/.*

  - url: /.*
    script: backend/server.js
