@startuml catsapp

' User class with attributes and role-based relationships
class User {
    - id: int
    - email: string
    - role: string
    - firstName: string
    - lastName: string
    - jobTitle: string
    - password: string
    - isEnable: boolean
    - createdBy: string
    - createDate: Date
    - lastUpdateBy: string
    - lastUpdateDate: Date

    + User(data: Object)
    + static cleanupUserData(userData: Object): void
    + static formatUserDetails(userData: Object): Object
    + static create(userData: Object): User
    + static findById(userId: int): User
    + static findByEmail(email: string): User
    + static returnAllUsers(): List<User>
    + changePassword(newPassword: string, initiatorId: int): Object
    + toggleUserStatus(isEnable: boolean, initiatorId: int): Object
    + update(updates: Object, initiatorId: int): Object
    + delete(): Object
}

class Address {
    -cityName : string
    -cityCode : string
    -address : string
    -postCode : string
    -longitude : string
    -latitude : string

    +constructor(cityName: string, cityCode: string, address: string, postCode: string, longitude: string, latitude: string)
    +getCityCode(cityName: string) : string
    +toDatabaseFormat() : object
}

class ContactInfo {
    -email : string[]
    -phoneNumber : string[]
    -website : string[]

    +constructor(email: string[], phoneNumber: string[], website: string[])
    +toDatabaseFormat() : object
}

class AssetDraft {
    -id : number
    -assetId : number
    -hasChildren : boolean
    -parentAssetDraftId : number
    -parentAssetDraftName : string
    -childrenIds : number[]
    -childrenNames : string[]
    -categoryIds : number[]
    -categoryNames : string[]
    -name : string
    -description : string
    -isVolunOpp : boolean
    -volunOppText : string
    -registrationNote : string
    -scheduleNote : string
    -socialWorkerOnlyNote : string
    -isWheelchairAcc : boolean
    -languagesOffered : string[]
    -scheduleType : string
    -format : string[]
    -status : string
    -createdEmail : string
    -createDate : date
    -address : Address
    -contactInfo : ContactInfo

    +constructor(data: object)
    +save() : void
    +getById(id: number) : AssetDraft
    +getAllPendingAssets() : AssetDraft[]
    +hasCreatedEmail() : boolean
    +sendReply(message: string) : void
    +changeState(newState: string) : void
    +editAssetDraft(updatedData: object) : void
    +toPlainData() : object
}


class Asset {
-id : number
-draftId : number
-hasChildren : boolean
-parentAssetId : number
-parentAssetName : string
-childrenIds : number[]
-childrenNames : string[]
-categoryIds : number[]
-categoryNames : string[]
-name : string
-description : string
-isVolunOpp : boolean
-volunOppText : string
-registrationNote : string
-scheduleNote : string
-socialWorkerOnlyNote : string
-isWheelchairAcc : boolean
-languagesOffered : string[]
-scheduleType : string
-format : string[]
-isEnable : boolean
-createdBy : number
-createdName : string
-createDate : date
-lastUpdateBy : number
-lastUpdateName : string
-lastUpdateDate : date
-address : Address
-contactInfo : ContactInfo

+constructor(data: object)
+save(who: number) : Promise<void>
+disableAsset() : Promise<void>
+editAsset(data: object, who: number) : Promise<void>
+toPlainData() : object
+getById(id: number) : Promise<Asset>
+getAllEnabledAssets() : Promise<Asset[]>
+getParentWithChildren(parentId: number) : Promise<Asset>
+formatUserData(assetData: object) : object
+searchAssets(categoryIds: number[], isVolunOpp: boolean, searchPhrase: string) : Promise<Asset[]>

}

 
class Category {
    +getAllCategories() : object[]
    +getCategoryTree() : object[]
    +getCategoryNamesByIds(ids: number[]) : string[]
}

' Utility class for handling emails
class EmailService {
    +sendEmail(to: string, subject: string, templateName: string, data: array): void
    +sendPasswordResetEmail(to: string, subject: string, templateName: string, data: array): void
    +loadTemplate(templateName: string, data:array): template
}

class EmailTemplates {
    [ReplyOnDraft.html]
    [AnotherTemplate.html]
    [NotificationTemplate.html]
}

' middleware class for authentication and rate limiting
class middleware {
    +authenticateJWT(request: Request): array
    +generateToken(user: user): string
    +generatePasswordResetToken(userId: int): string
    +globalRateLimiter(request: Request): void
    +userRateLimiter(request: Request): void
}

' Database for handling connections and queries
interface Database {
    +getConnection(): Promise<Connection>
    +query(sql: String, params: Array): Promise<[ResultSetHeader, any]>
    +close(): void
}

' API Routes as interfaces
interface UserRoutes {
    +PATCH /update/:id(id: string, updates: Record<string, any>, token: string): JSONobject
    +PATCH /togglestatus/:id(id: string, isEnable: boolean, token: string): JSONobject
    +POST /changepassword(newPassword: string, token: string): JSONobject
    +POST /sendpasswordreset(email: string): JSONobject
    +POST /register(newUser: Record<string, any>, token: string): JSONobject
    +DELETE /delete/:id(id: string, token: string): JSONobject
    +POST /login(email: string, password: string): JSONobject
    +GET /current(token: string): JSONobject
    +GET /usertable(token: string): array<JSONobject>
}

interface AssetRoutes {
    +POST /suggestNewAsset(newAssetData: JSONobject[]): { message: string }
    +POST /recommendChange(editAssetData: JSONobject[]): { message: string }
    +POST /addNewAsset(newAssetData: JSONobject[], token: string): { message: string }
    +POST /reviewStandaloneDraft(reviewedDraftId: string, reviewDecision: 'approved' | 'rejected', reviewComment?: string, token: string): { message: string }
    +POST /reviewMultilevelAsset(reviewedParentDraftId: string, reviewDecision: 'approved' | 'rejected', reviewComment?: string, token: string): { message: string }
    +PUT /editAssetDraft(editedAssetDraftData: JSONobject[], token: string): { message: string }
    +PUT /editAsset(editedAssetData: JSONobject[], token: string): { message: string }
    +GET /getAllPendingAssets(token: string): { pendingAssets: JSONobject[] }
    +GET /getAllEnabledAssets(): { allAssets: JSONobject[] }
    +GET /getAssetDraft(draftId: string, token: string): { assetDraft: JSONobject }
    +GET /getAsset(assetId: number): { asset: JSONobject }
    +GET /getParentAssetDraftTree(draftId: string, token: string): { assetDraft: JSONobject }
    +GET /getParentAssetTree(assetId: string): { asset: JSONobject }
    +GET /findAssets(categoryIds?: number[], isVolunOpp?: boolean, searchPhrase?: string): { assets: JSONobject[] }
}

interface CategoryRoutes {
    +GET /tree(token: string): JSONobject
}

' Server Class (CatsServer)
class catsserver {
  +port: number
  +app: Express
  +userRoutes: Router
  +categoryRoutes: Router
  +assetRoutes: Router
  +globalRateLimiter: middleware

  +constructor()
  +initializeMiddleware()
  +initializeRoutes()
  +startServer()
}

class dotenv {
  +config(): void
}


app.yaml -down-> catsserver : uses

catsserver -down-> dotenv : uses
catsserver -down-> UserRoutes : uses
catsserver -down-> CategoryRoutes : uses
catsserver -down-> AssetRoutes : uses


' Connecting routes to models and services
UserRoutes -down-> middleware : "uses"
AssetRoutes -down-> middleware : "uses"
CategoryRoutes -down-> middleware : "uses"
UserRoutes .down.> User : "manages"
AssetRoutes .down.> Asset : "manages"
AssetRoutes .down.> AssetDraft : "manages"
CategoryRoutes .down.> Category : "manages"
UserRoutes -down-> EmailService : "uses"

' Utility and middleware connections
EmailService -down-> EmailTemplates : "uses"

' AssetDraft has Address and ContactInfo (Aggregation)
AssetDraft "1" -down-> "1" Address : "has"
AssetDraft "1" -down-> "1" ContactInfo : "has"
AssetDraft "1" -down-> "1" Schedule : "has"
AssetDraft -down-> EmailService : "uses"

User -down-> Database : "uses"
AssetDraft -down-> Database : "uses"
Category -down-> Database : "uses"

AssetDraft ..> Category
AssetDraft ..> User

AssetDraft ..> assetDrafttest
User ..> usertest
Category ..> categorytest
middleware ..> middlewaretest

@enduml
